# Generated by Django 5.0.3 on 2024-04-15 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_type', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Добавени типове')),
                ('created_after', models.DateTimeField(blank=True, null=True)),
                ('category_list', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Избрани категории')),
                ('status_list', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Статус:')),
                ('name_contains', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Наименованието да съдържа:')),
                ('description_contains', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Описанието да съдържа:')),
                ('location_list', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='От район:')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itemfilter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_type', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Добавени типове')),
                ('created_after', models.DateTimeField(blank=True, null=True)),
                ('category_list', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Избрани категории')),
                ('status_list', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Статус:')),
                ('name_contains', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Наименованието да съдържа:')),
                ('description_contains', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Описанието да съдържа:')),
                ('location_list', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='От район:')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taskfilter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
