# Generated by Django 5.0.3 on 2026-07-15 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ОНЛАЙН', 'ONLINE'), ('ОФЛАЙН', 'OFFLINE'), ('НЕ БЕЗПОКОЙ', 'RELAXING'), ('ОТСЪСТВА', 'MISSING'), ('НЕАКТИВЕН', 'INACTIVE'), ('НЕИЗВЕСТЕН', 'UNKNOWN')], default='НЕИЗВЕСТЕН', max_length=20, verbose_name='Статус')),
                ('updated', models.DateTimeField(null=True)),
                ('banlist', models.ManyToManyField(related_name='banlist', to=settings.AUTH_USER_MODEL)),
                ('itembox', models.ManyToManyField(related_name='itembox', to='item.item')),
                ('missionbox', models.ManyToManyField(related_name='missions', to='task.task')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
