# Generated by Django 5.0.3 on 2024-04-15 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(null=True)),
                ('itembox', models.ManyToManyField(related_name='itembox', to='item.item')),
                ('missionbox', models.ManyToManyField(related_name='missions', to='task.task')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('waitingbox', models.ManyToManyField(related_name='waitings', to='task.task')),
            ],
        ),
    ]
