# Generated by Django 5.0.3 on 2024-04-16 07:56

import apps.player.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='banlist',
            field=models.ManyToManyField(related_name='banlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('ОНЛАЙН', 'ONLINE'), ('ОФЛАЙН', 'OFFLINE'), ('НЕ БЕЗПОКОЙ', 'RELAXING'), ('ОТСЪСТВА', 'MISSING'), ('НЕАКТИВЕН', 'INACTIVE'), ('НЕИЗВЕСТЕН', 'UNKNOWN')], default=apps.player.models.PlayerStatus['UNKNOWN'], max_length=20, verbose_name='Статус'),
        ),
    ]
