# Generated by Django 5.0.3 on 2024-04-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_banlist_alter_player_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='waitingbox',
        ),
    ]
