# Generated by Django 5.0.3 on 2024-05-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_remove_player_waitingbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('ОНЛАЙН', 'ONLINE'), ('ОФЛАЙН', 'OFFLINE'), ('НЕ БЕЗПОКОЙ', 'RELAXING'), ('ОТСЪСТВА', 'MISSING'), ('НЕАКТИВЕН', 'INACTIVE'), ('НЕИЗВЕСТЕН', 'UNKNOWN')], default='НЕИЗВЕСТЕН', max_length=20, verbose_name='Статус'),
        ),
    ]
