# Generated by Django 5.0.3 on 2024-05-31 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_alter_player_banlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='banlist',
            field=models.ManyToManyField(related_name='banlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
