# Generated by Django 5.0.3 on 2026-07-15 06:55

import apps.task.operate
import apps.tools.operate
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('player_id', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('task_type', models.CharField(choices=[('БЕЛЕЖНИК', 'БЕЛЕЖНИК'), ('РАБОТА', 'РАБОТА'), ('УСЛУГА', 'УСЛУГА'), ('ДИСКУСИЯ', 'ДИСКУСИЯ'), ('ЛЕКЦИЯ', 'ЛЕКЦИЯ'), ('ДРУГИ', 'ДРУГИ')], default='БЕЛЕЖНИК', max_length=20, verbose_name='Тип на задачата')),
                ('name', models.CharField(default='Няма заглавие', max_length=200, verbose_name='Заглавие')),
                ('description', models.CharField(default='Без описание', max_length=200, verbose_name='Кратко описание')),
                ('status', models.CharField(choices=[('ЧАКАЩА', 'PENDING'), ('ПРОЦЕС', 'IN_PROCESS'), ('ПАУЗА', 'PAUSED'), ('ЗАВЪРШЕНА', 'COMPLETED'), ('ОТМЕНЕНА', 'ABORTED'), ('НЕАКТИВНА', 'INACTIVE')], default=apps.task.operate.Status['PENDING'], max_length=20)),
                ('capacity', models.IntegerField(default=1, verbose_name='Необходими участници')),
                ('location', models.CharField(default='България', max_length=200, verbose_name='Място на изпълнение')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Валидна от')),
                ('valid_to', models.DateTimeField(default=apps.tools.operate.deadline, verbose_name='Валидна до')),
                ('general', models.BooleanField(default=False, verbose_name='Бедствие')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='catalogs.tcategory', verbose_name='Категория')),
                ('msgbox', models.ManyToManyField(related_name='task_post', to='message.message')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL)),
                ('waiting_list', models.ManyToManyField(related_name='listeners', to=settings.AUTH_USER_MODEL)),
                ('workers', models.ManyToManyField(related_name='workers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
