# Generated by Django 5.0.3 on 2024-04-15 13:43

import apps.task.operate
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('player_id', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('task_type', models.CharField(choices=[('ЛЕКЦИЯ', 'ЛЕКЦИЯ'), ('СЪВЕТ', 'СЪВЕТ'), ('УСЛУГА', 'УСЛУГА'), ('ОБЩА', 'ОБЩА'), ('ДИСКУСИЯ', 'ДИСКУСИЯ'), ('ЛИЧНА', 'ЛИЧНА')], default=apps.task.operate.TaskType['BASIC'], max_length=20, verbose_name='Тип на задачата')),
                ('category', models.CharField(default='Категория задачи', max_length=200, verbose_name='Категория')),
                ('name', models.CharField(default='Няма заглавие', max_length=200, verbose_name='Заглавие')),
                ('description', models.CharField(default='Без описание', max_length=200, verbose_name='Кратко описание')),
                ('status', models.CharField(choices=[('ЧАКАЩА', 'PENDING'), ('ПРОЦЕС', 'IN_PROCESS'), ('ПАУЗА', 'PAUSED'), ('ЗАВЪРШЕНА', 'COMPLETED'), ('ОТМЕНЕНА', 'ABORTED'), ('НЕАКТИВНА', 'INACTIVE')], default=apps.task.operate.Status['PENDING'], max_length=20)),
                ('capacity', models.IntegerField(default=1, verbose_name='Необходими участници')),
                ('location', models.CharField(default='България', max_length=200, verbose_name='Място на изпълнение')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Валидна от')),
                ('valid_to', models.DateTimeField(default=datetime.datetime(2024, 5, 15, 13, 43, 50, 133337, tzinfo=datetime.timezone.utc), verbose_name='Валидна до')),
                ('general', models.BooleanField(default=False, verbose_name='Бедствие')),
                ('msgbox', models.ManyToManyField(to='message.message')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL)),
                ('waiting_list', models.ManyToManyField(related_name='listeners', to=settings.AUTH_USER_MODEL)),
                ('workers', models.ManyToManyField(related_name='workers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
