# Generated by Django 5.0.3 on 2024-04-15 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 17, 5, 14, 854628, tzinfo=datetime.timezone.utc), verbose_name='Валидна до'),
        ),
    ]
