# Generated by Django 5.0.3 on 2024-04-16 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 7, 56, 6, 942898, tzinfo=datetime.timezone.utc), verbose_name='Валидна до'),
        ),
    ]
