# Generated by Django 5.0.3 on 2024-04-17 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 16, 41, 48, 786373, tzinfo=datetime.timezone.utc), verbose_name='Валидна до'),
        ),
    ]
