# Generated by Django 5.0.3 on 2024-04-20 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 19, 0, 52, 715447, tzinfo=datetime.timezone.utc), verbose_name='Валидна до'),
        ),
    ]
