# Generated by Django 5.0.3 on 2024-04-23 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_task_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 18, 26, 53, 550735, tzinfo=datetime.timezone.utc), verbose_name='Валидна до'),
        ),
    ]
