# Generated by Django 5.0.3 on 2024-04-24 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_alter_task_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 8, 19, 29, 801118, tzinfo=datetime.timezone.utc), verbose_name='Валидна до'),
        ),
    ]
