# Generated by Django 5.0.3 on 2024-04-25 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_alter_task_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 25, 8, 37, 49, 170215, tzinfo=datetime.timezone.utc), verbose_name='Валидна до'),
        ),
    ]
