# Generated by Django 5.0.3 on 2024-04-25 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_alter_task_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 25, 12, 24, 35, 798228, tzinfo=datetime.timezone.utc), verbose_name='Валидна до'),
        ),
    ]
