# Generated by Django 5.0.3 on 2024-05-02 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_alter_task_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('ЛЕКЦИЯ', 'ЛЕКЦИЯ'), ('СЪВЕТ', 'СЪВЕТ'), ('УСЛУГА', 'УСЛУГА'), ('ОБЩА', 'ОБЩА'), ('ДИСКУСИЯ', 'ДИСКУСИЯ'), ('ЛИЧНА', 'ЛИЧНА')], default='ОБЩА', max_length=20, verbose_name='Тип на задачата'),
        ),
        migrations.AlterField(
            model_name='task',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 17, 34, 27, 433886, tzinfo=datetime.timezone.utc), verbose_name='Валидна до'),
        ),
    ]
