# Generated by Django 5.0.3 on 2024-05-02 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_alter_task_task_type_alter_task_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 17, 38, 41, 694076, tzinfo=datetime.timezone.utc), verbose_name='Валидна до'),
        ),
    ]
