# Generated by Django 5.0.3 on 2024-05-08 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0027_alter_task_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 4, 56, 49, 768344, tzinfo=datetime.timezone.utc), verbose_name='Валидна до'),
        ),
    ]
