# Generated by Django 5.0.3 on 2024-05-11 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0029_alter_task_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 8, 26, 16, 938389, tzinfo=datetime.timezone.utc), verbose_name='Валидна до'),
        ),
    ]
