# Generated by Django 5.0.3 on 2024-05-12 07:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_rename_itemcategory_icategory'),
        ('task', '0030_alter_task_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='catalogs.tcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='task',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 7, 15, 16, 755420, tzinfo=datetime.timezone.utc), verbose_name='Валидна до'),
        ),
    ]
