# Generated by Django 5.0.3 on 2024-05-31 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0032_alter_task_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 5, 10, 6, 509177, tzinfo=datetime.timezone.utc), verbose_name='Валидна до'),
        ),
    ]
