# Generated by Django 5.0.3 on 2024-06-02 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0033_alter_task_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('БЕЛЕЖНИК', 'БЕЛЕЖНИК'), ('РАБОТА', 'РАБОТА'), ('УСЛУГА', 'УСЛУГА'), ('ДИСКУСИЯ', 'ДИСКУСИЯ'), ('ЛЕКЦИЯ', 'ЛЕКЦИЯ'), ('ДРУГИ', 'ДРУГИ')], default='ДРУГИ', max_length=20, verbose_name='Тип на задачата'),
        ),
        migrations.AlterField(
            model_name='task',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 8, 56, 37, 939975, tzinfo=datetime.timezone.utc), verbose_name='Валидна до'),
        ),
    ]
