# Generated by Django 5.0.3 on 2024-06-24 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0034_alter_task_task_type_alter_task_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('БЕЛЕЖНИК', 'БЕЛЕЖНИК'), ('РАБОТА', 'РАБОТА'), ('УСЛУГА', 'УСЛУГА'), ('ДИСКУСИЯ', 'ДИСКУСИЯ'), ('ЛЕКЦИЯ', 'ЛЕКЦИЯ'), ('ДРУГИ', 'ДРУГИ')], default='БЕЛЕЖНИК', max_length=20, verbose_name='Тип на задачата'),
        ),
        migrations.AlterField(
            model_name='task',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 3, 45, 20, 787780, tzinfo=datetime.timezone.utc), verbose_name='Валидна до'),
        ),
    ]
