# Generated by Django 5.0.3 on 2024-07-07 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0035_alter_task_task_type_alter_task_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 5, 51, 5, 793654, tzinfo=datetime.timezone.utc), verbose_name='Валидна до'),
        ),
    ]
