# Generated by Django 5.0.3 on 2024-04-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='TaskCategory',
        ),
        migrations.RemoveField(
            model_name='tasksubcategories',
            name='task_category',
        ),
        migrations.RemoveField(
            model_name='tasksubcatmember',
            name='task_sub_category',
        ),
        migrations.DeleteModel(
            name='TaskCategories',
        ),
        migrations.DeleteModel(
            name='TaskSubCategories',
        ),
        migrations.DeleteModel(
            name='TaskSubCatMember',
        ),
    ]
