# Generated by Django 5.0.3 on 2024-04-20 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_rename_category_taskcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsubcategories',
            name='item_category',
        ),
        migrations.RemoveField(
            model_name='itemsubcatmember',
            name='item_sub_category',
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalogs.itemcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemCategories',
        ),
        migrations.DeleteModel(
            name='ItemSubCategories',
        ),
        migrations.DeleteModel(
            name='ItemSubCatMember',
        ),
    ]
