# Generated by Django 5.0.3 on 2024-04-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_remove_itemsubcategories_item_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskCategory',
            new_name='TCategory',
        ),
    ]
