# Generated by Django 5.0.3 on 2024-04-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_rename_taskcategory_tcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCategory',
            new_name='ICategory',
        ),
    ]
