# Generated by Django 5.0.3 on 2024-04-15 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('message_text', models.TextField(default='Здравей!', max_length=500)),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('deliverybox', models.TextField(default='')),
                ('rating', models.IntegerField(default=0)),
                ('votebox', models.TextField(default='')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
