# Generated by Django 5.0.3 on 2024-05-02 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('image_id', models.CharField(max_length=10, unique=True)),
                ('image', models.ImageField(upload_to='uploads/pics')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='message.message')),
            ],
        ),
    ]
