# Generated by Django 5.0.3 on 2024-05-02 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='created_on',
        ),
        migrations.AlterField(
            model_name='picture',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='message.message'),
        ),
    ]
