# Generated by Django 5.0.3 on 2024-05-08 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_remove_picture_created_on_alter_picture_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='image_id',
        ),
    ]
