# Generated by Django 5.0.3 on 2024-05-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_remove_picture_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/pics'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
