# Generated by Django 5.0.3 on 2024-05-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_alter_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Снимка'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(default='', max_length=7000, verbose_name='Текст'),
        ),
    ]
