# Generated by Django 5.0.3 on 2024-07-07 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_remove_message_rating_message_downvotes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='deliverybox',
        ),
        migrations.RemoveField(
            model_name='message',
            name='votebox',
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_list',
            field=models.ManyToManyField(related_name='recipients', to=settings.AUTH_USER_MODEL),
        ),
    ]
