# Generated by Django 5.0.3 on 2024-04-15 13:43

import apps.item.operate
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('player_id', models.CharField(max_length=10)),
                ('item_type', models.CharField(choices=[('ПОДАРЪК', 'ПОДАРЪК'), ('ПОТРЕБНОСТ', 'ПОТРЕБНОСТ'), ('УСЛУГА', 'УСЛУГА')], default='ПОТРЕБНОСТ', max_length=20, verbose_name='Тип')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(default='Категория предмети', max_length=200, verbose_name='Категория')),
                ('status', models.CharField(choices=[('НОВ', 'НОВ'), ('УПОТРЕБЯВАН', 'УПОТРЕБЯВАН'), ('ДОБРО СЪСТОЯНИЕ', 'ДОБРО СЪСТОЯНИЕ'), ('ЛОШО СЪСТОЯНИЕ', 'ЛОШО СЪСТОЯНИЕ'), ('ИЗНОСЕН', 'ИЗНОСЕН'), ('ГОДЕН', 'ГОДЕН'), ('СЧУПЕН', 'СЧУПЕН'), ('БЕЗ ЗНАЧЕНИЕ', 'БЕЗ ЗНАЧЕНИЕ')], default=apps.item.operate.ItemStatus['GOOD'], max_length=20, verbose_name='Състояние')),
                ('name', models.CharField(default='Няма название', max_length=200, verbose_name='Какъв е')),
                ('description', models.CharField(default='Без описание', max_length=200, verbose_name='Описание')),
                ('quantity', models.IntegerField(default=1, null=True, verbose_name='Количество')),
                ('location', models.CharField(default='България', max_length=200, verbose_name='Локация')),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero', to=settings.AUTH_USER_MODEL)),
                ('msgbox', models.ManyToManyField(to='message.message')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
