# Generated by Django 5.0.3 on 2026-07-15 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='Здравей!', max_length=200)),
                ('msgtime', models.DateTimeField(auto_now_add=True)),
                ('target_id', models.CharField(default=None, max_length=20, null=True)),
                ('destination', models.CharField(max_length=50)),
                ('ntype', models.CharField(choices=[('event', 'Event'), ('status', 'Status'), ('chat', 'Chat'), ('unread post', 'Post')], max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='Здравей!', max_length=200)),
                ('msgtime', models.DateTimeField(auto_now_add=True)),
                ('target_id', models.CharField(default=None, max_length=20, null=True)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CHATS', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=50, unique=True)),
                ('users_in_room', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
