# Generated by Django 5.0.3 on 2024-04-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('message_text', models.TextField(default='Здравей!', max_length=500)),
                ('message_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
