# Generated by Django 5.0.3 on 2024-04-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='target_id',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
