# Generated by Django 5.0.3 on 2024-04-24 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notifications_target_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='group_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message_text',
            field=models.TextField(default='Здравей!', max_length=200),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='target_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('notifications_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notifications')),
                ('room_type', models.CharField(choices=[('item', 'Item'), ('task', 'Task')], default='task', max_length=50)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CHATS', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('notifications.notifications',),
        ),
    ]
