# Generated by Django 5.0.3 on 2024-04-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_chatmessage_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='room_type',
            field=models.CharField(choices=[('item', 'Item'), ('task', 'Task')], default='task', max_length=50),
        ),
    ]
