# Generated by Django 5.0.3 on 2024-04-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_chatmessage_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='message_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='message_time',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='room_type',
            field=models.CharField(choices=[('item', 'Item'), ('task', 'Task')], default='task', max_length=50),
        ),
    ]
