# Generated by Django 5.0.3 on 2024-04-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_rename_message_text_notifications_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='text',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='time',
            new_name='msgtime',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='room_type',
            field=models.CharField(choices=[('item', 'Item'), ('task', 'Task')], default='task', max_length=50),
        ),
    ]
