# Generated by Django 5.0.3 on 2024-04-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_rename_text_notifications_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='room_type',
        ),
        migrations.AddField(
            model_name='notifications',
            name='target_type',
            field=models.CharField(choices=[('item', 'Item'), ('task', 'Task')], default='task', max_length=50),
        ),
    ]
