# Generated by Django 5.0.3 on 2024-04-25 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_remove_chatmessage_room_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='target_type',
            field=models.CharField(choices=[('item', 'Item'), ('task', 'Task')], default='task', max_length=50),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=50, unique=True)),
                ('users_in_room', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
