# Generated by Django 5.0.3 on 2024-04-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notifications_target_type_chatroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='target_type',
        ),
    ]
