# Generated by Django 5.0.3 on 2024-04-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_remove_notifications_target_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sender',
            new_name='owner',
        ),
    ]
