# Generated by Django 5.0.3 on 2024-04-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_alter_chatmessage_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
