# Generated by Django 5.0.3 on 2024-04-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='ntype',
            field=models.CharField(choices=[('event', 'Event'), ('status', 'Status'), ('chat', 'Chat'), ('unread post', 'Post')], max_length=200, null=True),
        ),
    ]
