# Generated by Django 5.0.3 on 2024-04-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_notifications_ntype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='group_name',
            new_name='destination',
        ),
    ]
